services:
  node1:
    build: ./node
    container_name: node1
    networks:
      - ansible
    ports:
      - "2221:22"
      - "3221:80"

  node2:
    build: ./node
    container_name: node2
    networks:
      - ansible
    ports:
      - "2222:22"
      - "3222:80"

  node3:
    build: ./node
    container_name: node3
    networks:
      - ansible
    ports:
      - "2223:22"
      - "3223:80"

networks:
  ansible:
    driver: bridge
