version: '3.8'

services:
  node1:
    build: ./node
    container_name: node1
    networks:
      - ansible
    ports:
      - "2221:22"

  node2:
    build: ./node
    container_name: node2
    networks:
      - ansible
    ports:
      - "2222:22"

  node3:
    build: ./node
    container_name: node3
    networks:
      - ansible
    ports:
      - "2223:22"

networks:
  ansible:
    driver: bridge
